### ISSUE TITLE
Questions about edges and acc_idxs

### ISSUE THREAD

**Issue by YangYangGirl** [bleakie/CenterMulti#14]

**Comment by YangYangGirl** [comment]
![image](https://user-images.githubusercontent.com/32426369/80295805-56e00980-87a8-11ea-986b-98ff5d0a69ee.png)
![image](https://user-images.githubusercontent.com/32426369/80295811-619a9e80-87a8-11ea-83ea-5d2106be2113.png)


When it comes to retinaface dataset, we need to change the num of keypoints from 17 to 5. How to change the parameters of edges and acc_idxs ?  I can not grasp these details , could you help me?

**Comment by bleakie** [comment]
[1,2,3,4,5]

**Comment by HDYYZDN** [comment]
想请问一下，acc_idxs的含义是什么，希望尽快得到回复，谢谢
