### ISSUE TITLE
可以提供下人脸mobilenetv2模型对应的mobilenetv2_512x512.yaml文件吗？

### ISSUE THREAD

**Issue by gm19900510** [bleakie/CenterMulti#3]

**Comment by gm19900510** [comment]
https://github.com/tensorboy/centerpose/blob/master/experiments/mobilenetv2_512x512.yaml的文件可以直接使用吗？能指出所需修改项吗？

**Comment by bleakie** [comment]
可以傻瓜式训练，更好的结果需要自己调参
