### ISSUE TITLE
landmark相关问题？

### ISSUE THREAD

**Issue by SyGoing** [bleakie/CenterMulti#7]
1、原始的fcenterface虽然具有关键点，但是其准确度要比mtcnn的差的，那么如果按照你这样修改之后，训练的效果有没有和mtcnn的对比过呢？
2、原始模型结构上是mobilenetv2，但是relu6替换成了relu，看你这边给出的backbone,用的relu6，有对比过二者在训练上的差别么

**Comment by bleakie** [comment]
1.按照我训练的结果和centerface和retinaface比较过，我的都更准
2.relu6可以替换成relu，结果差距不大

**Comment by SyGoing** [comment]
谢谢回复，我这边只是用centernet训练了几个版本不带关键点  检测率也比原始centerface

**Comment by bleakie** [comment]
关键点加进去就相当于multipose，会对检出率有帮助

**Comment by SyGoing** [comment]
只是说这个时候的关键点不再是人体的而是人脸的  看了下改动也不大，。对于单纯检测我直接voc格式的 因为如果有新任务可以标注直接训练的

**Comment by byh1990** [comment]
> 谢谢回复，我这边只是用centernet训练了几个版本不带关键点 检测率也比原始centerface

你这边训练的结果超过了官方的指标么？指标咋样啊？我们这边的指标才76%，还在调整的过程中，能加你个联系方式么？我的邮箱byh961215348@163.com,能不能发一个联系方式呢？直接在上面弄手机号不太好吧

**Comment by bleakie** [comment]
没有测试具体指标，因为widerface里面有一些人脸质量不适合人脸识别，所以过滤掉了，很难做统一的评价

**Comment by byh1990** [comment]
> 没有测试具体指标，因为widerface里面有一些人脸质量不适合人脸识别，所以过滤掉了，很难做统一的评价

相当的给力啊，像你这样的大牛学习啊，只能怨自己太菜了，你的工作很有意义，优秀皆开源，在下佩服

**Comment by byh1990** [comment]
CenterMulti: 人脸检测+landmark可参考CenterMulti，效果更好，而且支持landmark的confidence
1.怎么给landmark增加confidence的训练？
2.在centermulti里面可以参考哪一个backbone？能输出confidence的是哪一个？

**Comment by bleakie** [comment]
1.landmark可以理解为姿态估计的每个关键点，参见multi_pose.py  def show_results(self, debugger, image, results)
2.所有backbone都可以输出conference

**Comment by Devincool** [comment]
请问landmark能像openpose那样输出每个点的置信度么

**Comment by bleakie** [comment]
sure
