### ISSUE TITLE
训练相关问题

### ISSUE THREAD

**Issue by byh1990** [bleakie/CenterMulti#8]
1.请问，您训练shufflenetv2网络耗时多久？什么硬件？训练了几个epoch？
我现在用2080卡，pytorch训练shufflenetv2，每个epoch需要2小时左右，正常么？谢谢

**Comment by bleakie** [comment]
这个要看你的数据有多少，如果图片较多，batchsize较大，自然速度很慢，ps：我用的1080ti*4，1w张图，一个epoch大约10min

**Comment by byh1990** [comment]
> 这个要看你的数据有多少，如果图片较多，batchsize较大，自然速度很慢，ps：我用的1080ti*4，1w张图，一个epoch大约10min

我忘了说了，用的imagenet数据集，对不起，我的失误，说的不详细，还望见谅，非常感谢你的回答，不过却是佩服你的能力啊，向你学习啊。

**Comment by bleakie** [comment]
shufflenetv2效果不如mobilenetv2，速度差不多，加速起来也方便
