### ISSUE TITLE
骨干网络应用问题

### ISSUE THREAD

**Issue by PowerXiaoBei** [bleakie/CenterMulti#9]
mobilenetV2,mobilenetV3,efficientdet and shufflenetv2 。Can it be applied directly to target detection？How do I use it for target detection？怎样把新加的骨干网络用于目标检测的训练，直接配置进去，出现问题。谢谢大佬

**Comment by bleakie** [comment]
有的网络需要DCN，配置的时候编译进去，mobilenetV2不需要，可以直接使用

**Comment by czy112** [comment]
你好，请问在更换主干网络之后怎么开始训练呢？能不能指导下我？
